config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :comments
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # , ActiveAdmin::Devise.config
  # devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'pages#index', as: 'home'
  get 'add', to: 'carts#add', as: 'add_to_cart'
  get 'quantity', to: 'carts#change_quantity'
  get 'buy', to: 'orders#add_order'
  # get 'category', to: 'pages#category', as: 'category'
  resources :orders
  get 'order_list', to: 'orders#index', as: 'order_index'
  post 'valid_email', to: 'orders#valid_email', as: 'valid_email'
  resources :carts
  resources :pages
  resources :comments
  resources :categories, only: :show do
    get 'range', on: :collection
    get 'search', on: :collection
    get 'searchdo', on: :collection
    resources :products, only: %i[index show]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
end

app/controllers/carts_controller.rb
# frozen_string_literal: true

class CartsController < ApplicationController
  before_action :set_user
  before_action :find_product, only: [:change_quantity]
  before_action :authenticate_user!

  def index
    @pagy, @items_list = pagy(@user.carts, items: 5)
  end

  def add
    cart_params = permitted_cart_params.merge(user_id: @user.id)
    @product = Cart.find_by(cart_params.except(:quantity))
    if @product.present?
      @product.increment(:quantity)
      @product.save
    else
      Cart.create(cart_params)
    end
    render 'carts/cart_add', product: @product
  end

  def destroy
    @cart = @user.carts.find(params[:id])
    @cart_id = @cart.id
    render 'carts/cart_destroy'
    @cart.destroy


  end

  def change_quantity
    case params[:argument]
    when '-'
      @item.quantity <= 1 ? @item.quantity = 1 : @item.decrement(:quantity)
    when '+'
      @item.increment(:quantity)
    end
    @item.save
    @price = Product.find(@item.item).price * @item.quantity
    render 'carts/quantity'
  end

  private

  def set_user
    @user = current_user
  end

  def permitted_cart_params
    params.permit(:item, :quantity)
  end

  def find_product
    @item = Cart.find(params[:id])
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_block_info_cart.html.erb
<div class="modal modal-centered" id="addProduct" tabindex="1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Product added to cart</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <div class="row">
          <h4><%= product.name %></h4>
        </div>
        <div class="row">
          <div class="col"><%= image_tag(product.photo, class:"img-fluid") %></div>
          <div class="col">
            <div class="btn-group me-2" role="group" aria-label="Second group">
              <%cart_item = current_user.carts.find_by(item: product.id) %>
              <%= link_to '-', quantity_path(argument: '-', id: cart_item.id), remote: true, type: "button",  class: "btn btn-secondary" %>
              <div id="quantity_id_<%= cart_item.id %>" class="alert alert-secondary" role="alert">
                <%= cart_item.quantity %>
              </div>
              <%= link_to '+', quantity_path(argument: '+', id: cart_item.id), remote: true, type: "button",  class: "btn btn-secondary" %>
            </div>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <%= link_to 'You cart', '/carts', class: "btn btn-info" %>
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Continue shopping</button>
      </div>
    </div>
  </div>
</div>

app/views/carts/cart_add.js.erb
$('#cart_button').replaceWith('<a class="btn btn-info btn-lg" role="button" style="color: #ffffff" data-bs-target="#addProduct" data-bs-toggle="modal" data-remote="true" href="#">In cart</a>');
$('main').prepend("<%= j render('carts/block_info_cart', product: Product.find(params[:item]))%>")

app/views/carts/cart_destroy.js.erb
$('#cart_<%= @cart_id %>').remove();

app/views/carts/index.html.erb
<div class="container-sm">
  <h1>Cart</h1>
  <% @items_list.each do |cart_item| %>
    <% product = Product.find(cart_item.item) %>
    <div id="cart_<%= cart_item.id %>" class="shadow p-3 mb-5 rounded  bg-light bg-gradient border border-1">
      <div class="row bcart_item-bottom bcart_item-4 justify-content-between">
        <div class="col-auto display-6"><%= product.name %></div>
        <div class="col-auto">
          <%= link_to 'Delete', cart_item, class: 'btn btn-danger',  method: :delete, data: { confirm: 'Are you sure?' }, remote: true %>
        </div>
      </div>
      <div class="row mt-3 justify-content-around">
        <div class="col">
          <%= image_tag(product.photo, class: "rounded border border-1 w-50" )%>
        </div>
        <div class="col">
          <div class="row">Сustomer email: <%= User.find(cart_item.user_id).email %></div>
          <div class="row display-6 mb-5 mt-3 align-items-start justify-content-start">
            <div class="col-auto"><%= link_to '-', quantity_path(argument: '-', id: cart_item.id), remote: true,
                                              class: 'btn btn-secondary btn-lg'%></div>
            <div id="quantity_id_<%= cart_item.id %>" class="col-auto">
              <%= cart_item.quantity %>
            </div>
            <div class="col-auto"><%= link_to '+', quantity_path(argument: '+', id: cart_item.id), remote: true,
                                              class: 'btn btn-secondary btn-lg'%></div>
          </div>
          <div class="row display-6 mt-3" id="price_<%= cart_item.id %>">Price: <%=number_to_currency(((product.price * cart_item.quantity).round(2)),
                                                                                                      unit:"UAH", separator: ",", format: "%n%u" )  %></div>
          <div class="row mt-3">
            <%= link_to 'Buy now',
                        new_order_path(product: product.id, quantity: cart_item.quantity, from_cart: true, cart_id: cart_item.id),
                        class: 'btn btn-success btn-lg w-50', id: "buy_button",
                        role: "button", style: "color: white"%>
          </div>
        </div>
      </div>
    </div>
    </div>

  <% end %>
  <%= pagy_bootstrap_nav(@pagy).html_safe if @pagy.present? %>
  </div>  </div>

app/views/carts/quantity.js.erb
$('#quantity_id_<%= @item.id %>').empty();
$('#quantity_id_<%= @item.id %>').append('<%= @item.quantity %>');
$('#price_<%= @item.id %>').empty();
$('#price_<%= @item.id %>').append('Price: <%=number_to_currency(((@price).round(2)), unit:"UAH", separator: ",",format: "%n %u" )  %>');