config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :comments
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # , ActiveAdmin::Devise.config
  # devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'pages#index', as: 'home'
  get 'add', to: 'carts#add', as: 'add_to_cart'
  get 'quantity', to: 'carts#change_quantity'
  get 'buy', to: 'orders#add_order'
  # get 'category', to: 'pages#category', as: 'category'
  resources :orders
  get 'order_list', to: 'orders#index', as: 'order_index'
  post 'valid_email', to: 'orders#valid_email', as: 'valid_email'
  resources :carts
  resources :pages
  resources :comments
  resources :categories, only: :show do
    get 'range', on: :collection
    get 'search', on: :collection
    get 'searchdo', on: :collection
    resources :products, only: %i[index show]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
  has_ancestry
  has_many :products
  validates :name, presence: true

end

app/controllers/categories_controller.rb
# frozen_string_literal: true

class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show]
  before_action :force_json, only: :search

  def index
    # @categories = Category.all
    @categories = Category.order(:name).where('name like ?', "%#{params[:term]}%")
    render json: @categories.map(&:name)
  end

  def new
    @category = Category.new
  end

  def show
    @categories_list = Category.all
    @product_list = @category.products
    products_list
  end

  def create
    @category = Category.new(category_params)
    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def searchdo
    @categories_list = Category.all
    @product_list = Product.where('name LIKE ?', "%#{params[:product_name.to_s]}%")
    products_list
    render :'categories/show'
  end

  def to_param
    name
  end
  def search
    q = params[:q].downcase
    @products = Product.where('name LIKE ? or about LIKE ?', "%#{q}%", "%#{q}%").limit(5)
  end

  private

  def force_json
    request.format = :json
  end

  def sort_column
    Product.column_names.include?(params[:sort]) ? params[:sort] : nil
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : nil
  end

  def set_category
    @category = Category.find(params[:id])
  end

  def minimum
    params[:min].nil? || params[:min] == '' ? 0 : params[:min]
  end

  def maximum
    params[:max].nil? ? 99_999_999_999 : params[:max]
  end

  def category_params
    params.require(:category).permit(:name, :parent_id, :image)
  end

  def products_list
    @products = if params[:min].nil? && params[:max].nil?
                  sort_column && sort_direction ? @product_list.order("#{sort_column} #{sort_direction}") : @product_list
                else
                  if !(sort_column && sort_direction)
                    @product_list.min_price(minimum).max_price(maximum).order(sort_column.to_s)
                  else @product_list.min_price(minimum).max_price(maximum).order("#{sort_column} #{sort_direction}")
                  end
                end
    @pagy, @products = pagy(@products)

  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<div class="col-3 left_side_bar">
  <div class="mt-3">
    <ul class="list-group">
      <% @categories_list.roots.each do |category_type|%>
        <li style="list-style-type: none;" id="parent_block_<%= category_type.id %>">
          <% name = Category.find_by(name: category_type.name) %>
          <%= link_to category_type.name, category_path(category_type, name.name),
                      class:"list-group-item list-group-item-action", id:category_type.name  %>
          <ul class="list-group px-3 subcategory">
            <% category_type.children.each do |category_child| %>
              <li class="child_block_<%= category_type.id %>"  style="display: none; list-style-type: none;" >
                <% name = Category.find_by(name: category_child.name) %>
                <%= link_to category_child.name, category_path(category_child, name.name),
                            class:"list-group-item list-group-item-action px-2", id:category_child.name  %>
              </li>
            <% end %>
          </ul>
        </li>
        <script>
            var li = document.getElementById("parent_block_<%= category_type.id %>");
            li.addEventListener('mouseenter', function (){
                $('.child_block_<%= category_type.id %>').show('slow');
            })

            li.addEventListener('mouseleave', function (){
                $('.child_block_<%= category_type.id %>').hide('slow');
            })

        </script>
      <% end %>
    </ul>
  </div>
  <hr>
  <div>
    <p>Contact info</p>
  </div>
</div>

app/views/categories/create.html.erb
<h1>create</h1>

app/views/categories/index.html.erb
<h1>CATEGORIES</h1>
<%= link_to 'Add new category', new_category_path(), class: 'btn btn-info btn-sm', role: "button", style: "color: white" %>
<%@categories.each do |cat|%>
  <div><%=cat.name %></div>
<% end %>

app/views/categories/show.html.erb
<script>
    $( document ).ready(function() {
        <% if @category.parent_id.present? %>
        $('.child_block_<%= @category.parent_id %>').show();
        $('.child_block_<%= @category.parent_id %>').removeClass( "child_block_<%= @category.parent_id %>" );
        <% end %>
        $("#<%= params[:sort] %>").addClass("active");
        <% if @category.present? %>
        $("#<%= @category.name %>").addClass("active");
        <% end %>
    })
</script>
<div class="row">
  <%= render 'categories/category'  %>
  <div class="col-9 ps-3 mt-5">
    <h1><%=  @category.present? ? @category.name : "Search result for: #{params[:product_name]}"%></h1>
    <div class="row border border-3 p-2 mb-3 rounded align-items-center shadow-sm bg-white rounded">
      <nav style="--bs-breadcrumb-divider: url(&#34;data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8'%3E%3Cpath d='M2.5 0L1 1.5 3.5 4 1 6.5 2.5 8l4-4-4-4z' fill='currentColor'/%3E%3C/svg%3E&#34;);" aria-label="breadcrumb">
        <ol class="breadcrumb mb-0">
          <li class="breadcrumb-item">
            <%= link_to 'Main', home_path%>
          </li>
          <li class="breadcrumb-item">
            <%= @category.name %>
          </li>
        </ol>
      </nav>
    </div>
    <div class="row mx-1 p-3 bg-light align-items-start alert alert-secondary">
      <div class="col-lg-4 col-sm-auto btn-group">
        <%= sortable "name",  params[:min], params[:max], params[:product_name] %>
        <%= sortable "price", params[:min], params[:max], params[:product_name] %>
        <%= sortable "created_at", params[:min], params[:max], params[:product_name], "Created" %>
      </div>
      <div class="col-lg-3 col-sm-0"></div>
      <div class="col-lg-5 col-sm-auto">
        <%= form_with url: @category, class: "d-flex", method: :get, local:true do |f|  %>
          <div class="input-group mb-3">
            <span class="input-group-text">From:</span>
            <%= f.text_field :min, id: :min, class: "form-control", placeholder:"min" , value: params[:min], type: "number" %>
            <span class="input-group-text">to:</span>
            <%= f.text_field :max, id: :max, class: "form-control", placeholder:"max", value: params[:max], type: "number" %>
            <%= f.submit "Filter", class: "btn btn-outline-success" %>
          </div>
          <%= f.hidden_field :sort, id: :sort, value: params[:sort] %>
          <%= f.hidden_field :directions, id: :directions, value: params[:directions]  %>
        <%end %>
      </div>
    </div>
    <div class="row ms-lg-4">
      <% if @product_list.any? %>
        <%@products.each do |product| %>
          <div class="card border-light" style="max-width: 14rem;">
            <%= link_to image_tag(url_for(product.photo), class: "card-img-top", alt: product.config ),
                        category_product_path(category, product, name.name) if product.photo.present?%><div class="card-body">
              <% name = Product.find_by(name: product.name) %>
              <p class="card-text"><%= link_to product.name, category_product_path(product.category_id, product, name.name), class: "link-danger" %></p>
              <h6 class="card-title"><%= number_to_currency(product.price, unit:"UAH", separator: ",", format: "%n%u" ) %> </h6>
            </div>
          </div>
        <% end %>
        <%= pagy_bootstrap_nav(@pagy).html_safe if @pagy.present? %>
      <%else %>
        <div class="alert alert-secondary align-items-center" role="alert">
          At this moment in this category nothing added
        </div>
      <% end %>
    </div>
  </div>

</div>
</div>