config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :comments
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # , ActiveAdmin::Devise.config
  # devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'pages#index', as: 'home'
  get 'add', to: 'carts#add', as: 'add_to_cart'
  get 'quantity', to: 'carts#change_quantity'
  get 'buy', to: 'orders#add_order'
  # get 'category', to: 'pages#category', as: 'category'
  resources :orders
  get 'order_list', to: 'orders#index', as: 'order_index'
  post 'valid_email', to: 'orders#valid_email', as: 'valid_email'
  resources :carts
  resources :pages
  resources :comments
  resources :categories, only: :show do
    get 'range', on: :collection
    get 'search', on: :collection
    get 'searchdo', on: :collection
    resources :products, only: %i[index show]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_one_attached :photo
  has_many :comments, dependent: :destroy

  scope :min_price, ->(min) { where('price >= ?', min) }
  scope :max_price, ->(max) { where('price <= ?', max) }

  def rating
    return 'no rating at the moment' if comments.empty?
    return (comments.sum(&:rating).to_f / comments.count).round(1) if comments.present?
  end

  def product_name
    product.try(:name)
  end

  def product_name=(name)
    self.product = Product.find_by_name(name) if name.present?
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :find_category, only: [:show]
  before_action :set_product, only: [:show]


  def index; end

  def show; end

  def to_param
    name
  end
  private


  def find_category
    @category = Category.find(params[:category_id])
  end

  def set_product
    @product = @category.products.find(params[:id])
  end


  def product_params
    params.require(:product).permit(:category_id, :price, :photo, :about, :config, :article, :factory, :name)
  end


end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_product.html.erb
<div class="card border-light m-0" style="max-width: 12rem;">
  <% name = Product.find_by(name: product.name) %>
  <%= link_to image_tag(url_for(product.photo), class: "card-img-top", alt: product.config ),
              category_product_path(category, product, name.name) if product.photo.present?%>
  <div class="card-body align-items-center">
    <p class="card-text"><%= link_to product.name, category_product_path(category, product, name.name), class: "link-danger" %></p>
    <h6 class="card-title"><%= number_to_currency(product.price, unit:"UAH", separator: ",", format: "%n%u" ) %> </h6>
  </div>
</div>

app/views/products/show.html.erb
<% if current_user.nil? %>
  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Please log in or sing in</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          You cannot perform this action until you register
        </div>
        <div class="modal-footer">
          <%= link_to 'Log in', "/users/sign_up", class: "btn btn-secondary"%>
          <%= link_to 'Sign in', "/users/sign_in", class: "btn btn-secondary"%>
        </div>
      </div>
    </div>
  </div>
<% end %>

<div class="container mt-2">
  <div class="row border border-3 rounded align-items-center shadow-sm bg-white rounded">
    <nav style="--bs-breadcrumb-divider: url(&#34;data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8'%3E%3Cpath d='M2.5 0L1 1.5 3.5 4 1 6.5 2.5 8l4-4-4-4z' fill='currentColor'/%3E%3C/svg%3E&#34;);" aria-label="breadcrumb">

      <ol class="breadcrumb mb-0 py-3 ms-2">
        <li class="breadcrumb-item">
          <%= link_to 'Main', home_path%>
        </li>
        <li class="breadcrumb-item">
          <%= link_to @category.name, category_path(@category, @category.name)%>
        </li>
        <li class="breadcrumb-item active" aria-current="page">
          <%= @product.name %>
        </li>
      </ol>
    </nav>
  </div>

  <div class="row justify-content-between align-items-center">
    <div class="col-auto me-auto">
      <h3><%=@product.name %></h3>
      <span class="h5">Rating </span><span class="badge bg-secondary h5"><%= @product.rating %> / 5</span>
    </div>
    <div class="col-auto "><h5><span class="badge bg-secondary">Article: <%=@product.article %></span></h5></div>
  </div>

  <hr>
  <div class="row">
    <div class="col-sm">
      <%= image_tag(@product.photo, class:"img-fluid", style: 'min-width: 28rem') if product.photo.present? %>
    </div>
    <div class="col-sm">
      <div class="row justify-content-between mt-2 mb-3 jumbotron ">
        <div class="col-auto align-self-center">
          <h1 class="display-6"><strong><%= number_to_currency(@product.price, unit:"UAH", separator: ",", format: "%n%u" ) %></strong></h1>
        </div>
        <div class="col-auto align-self-center">
          <% if current_user.present? %>
            <%= link_to 'Add to cart',
                        add_to_cart_path(item: @product.id),
                        class: 'btn btn-info btn-lg', id: "cart_button",
                        role: "button", style: "color: white",
                        remote: true,
                        data: { "bs-target": "#addProduct", "bs-toggle": "modal" }%>

            <%= link_to 'Buy now',
                        new_order_path(product: @product.id),
                        class: 'btn btn-success btn-lg', id: "buy_button",
                        role: "button", style: "color: white"%>
          <% else %>
            <button type="button" class="btn btn-info btn-lg" data-bs-toggle="modal" data-bs-target="#exampleModal">
              Add to cart
            </button>
            <button type="button" class="btn btn-success btn-lg" data-bs-toggle="modal" data-bs-target="#exampleModal">
              Buy now
            </button>
          <% end %>
        </div>
      </div>
      <div class="row jumbotron mb-0">
        <h4>Config:</h4>
        <div class="col"> <%=@product.config %></div>
      </div>
      <br>
      <div class="row jumbotron mt-0">
        <h4>Factory:</h4>
        <div class="col"> <%=@product.factory %></div>
      </div>
    </div>
  </div>
  <hr>
  <div class="row mx-3">
    <%= @product.about %>
  </div>
  <hr>
  <% if current_user.present? %>
    <div><%= link_to 'Add comment',  new_comment_path(product_id: @product.id),
                     method: :get, class: 'btn btn-success btn-lg' %></div>
  <% else %>
    <div class="alert alert-danger">
      only registered user can left comment
    </div>
  <% end %>
  <div class="row mt-4">
    <% if @product.comments.any? %>
      <div>
        <% @product.comments.each do |comment| %>
          <div class="row border border-3 rounded p-2 mb-3 shadow-sm bg-white rounded">
            <div class="row justify-content-between mb-1">
              <div class="col-auto me-2"><%= User.find(comment.user.id).email %></div>
              <div class="col-auto badge bg-secondary"><%= comment.rating %> / 5</div>
            </div>
            <hr>
            <div class="row"><%= comment.body %></div>
            <div class="row justify-content-end">
              <div class="col-auto">
                <% if current_user.id == comment.user_id %>
                  <%= link_to "Delete", comment, method: :delete, class: 'btn btn-danger btn-sm', role: "button", style: "color: white"  %>
                  <%= link_to 'Edit', edit_comment_path(comment), class: 'btn btn-info btn-sm', role: "button", style: "color: white" %>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <% else %>
      <div class="alert alert-secondary">
        At this moment no comments
      </div>
    <% end %>
  </div>

</div>