config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :comments
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # , ActiveAdmin::Devise.config
  # devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'pages#index', as: 'home'
  get 'add', to: 'carts#add', as: 'add_to_cart'
  get 'quantity', to: 'carts#change_quantity'
  get 'buy', to: 'orders#add_order'
  # get 'category', to: 'pages#category', as: 'category'
  resources :orders
  get 'order_list', to: 'orders#index', as: 'order_index'
  post 'valid_email', to: 'orders#valid_email', as: 'valid_email'
  resources :carts
  resources :pages
  resources :comments
  resources :categories, only: :show do
    get 'range', on: :collection
    get 'search', on: :collection
    get 'searchdo', on: :collection
    resources :products, only: %i[index show]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
end

app/models/category.rb
class Category < ApplicationRecord
  has_ancestry
  has_many :products
  validates :name, presence: true

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :product
  validates_presence_of :body, :rating
  validates_uniqueness_of :user_id, scope: :product_id
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user

  VALID_QUANTITY = /\A\d\z/i
  validates :quantity, presence: true#, format: { with: VALID_QUANTITY }
  validates :user_id, :item, presence: true

  scope :in_process, -> { where('status = 0') }
  scope :confirmed, -> { where('status = 1') }
  scope :canceled, -> { where('status = 2') }
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_one_attached :photo
  has_many :comments, dependent: :destroy

  scope :min_price, ->(min) { where('price >= ?', min) }
  scope :max_price, ->(max) { where('price <= ?', max) }

  def rating
    return 'no rating at the moment' if comments.empty?
    return (comments.sum(&:rating).to_f / comments.count).round(1) if comments.present?
  end

  def product_name
    product.try(:name)
  end

  def product_name=(name)
    self.product = Product.find_by_name(name) if name.present?
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :validatable,
         :recoverable, :rememberable, :omniauthable, omniauth_providers: [:github] #, :twitter

  has_many :orders
  has_many :carts, dependent: :destroy
  has_many :comments, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable



  def self.from_omniauth(auth)
    puts auth
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      puts user
      user.provider = auth.provider
      user.uid = auth.uid
      user.password = Devise.friendly_token[0, 20]
      !auth.info.email.nil? ? user.email = auth.info.email : user.email = auth.info.nickname
    end
  end
end

app/controllers/carts_controller.rb
# frozen_string_literal: true

class CartsController < ApplicationController
  before_action :set_user
  before_action :find_product, only: [:change_quantity]
  before_action :authenticate_user!

  def index
    @pagy, @items_list = pagy(@user.carts, items: 5)
  end

  def add
    cart_params = permitted_cart_params.merge(user_id: @user.id)
    @product = Cart.find_by(cart_params.except(:quantity))
    if @product.present?
      @product.increment(:quantity)
      @product.save
    else
      Cart.create(cart_params)
    end
    render 'carts/cart_add', product: @product
  end

  def destroy
    @cart = @user.carts.find(params[:id])
    @cart_id = @cart.id
    render 'carts/cart_destroy'
    @cart.destroy


  end

  def change_quantity
    case params[:argument]
    when '-'
      @item.quantity <= 1 ? @item.quantity = 1 : @item.decrement(:quantity)
    when '+'
      @item.increment(:quantity)
    end
    @item.save
    @price = Product.find(@item.item).price * @item.quantity
    render 'carts/quantity'
  end

  private

  def set_user
    @user = current_user
  end

  def permitted_cart_params
    params.permit(:item, :quantity)
  end

  def find_product
    @item = Cart.find(params[:id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_product, only: :create
  before_action :set_comment, only: [:edit, :destroy, :update]
  def new
    @comment = Comment.new(product_id: params[:product_id])
  end

  def create

    comment_params = permitted_comment_params.merge(user_id: current_user.id)
    @comment = @product.comments.create(comment_params)
    if @comment.save
      redirect_to category_product_path( id: @comment.product.id, category_id: @comment.product.category_id)
    else
       render :new
    end
  end

  def edit; end

  def update
    if @comment.update(permitted_comment_params)
         redirect_to category_product_path( id: @comment.product.id, category_id: @comment.product.category_id),
                     notice: 'Comment was successfully edited.'
    else
       render :edit
    end
  end

  def destroy
    @comment.destroy
  end

  private

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def find_product
    @product = Product.find(params[:comment][:product_id])
  end

  def permitted_comment_params
    params.require(:comment).permit(:body, :rating)
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  before_action :set_user
  before_action :authenticate_user!


  def index
    @pagy, @orders = pagy(@user.orders, items: 5)
  end

  def new
    @order = Order.new
    @product = Product.find(params[:product])
  end
  
  def create
    @product = Product.find(params[:order][:item])
    order_params = permitted_order_params.merge(user_id: @user.id)
    @order = Order.new(order_params)
    respond_to do |format|
      if @order.save
        OrdersMailer.with(user: @user, product: @product, order: @order).complete_order.deliver_now
        format.html { redirect_to order_index_url, notice: 'order was successfully created.' }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_user
    @user = current_user
  end

  def permitted_order_params
    params.require(:order).permit(:item, :quantity)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
    @pagy, @categories = pagy(Category.all)
    @categories_list = Category.all
  end

  def admin
    @pagy, @categories = pagy(Category.all)
    @products = Product.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ShopS</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/easy-autocomplete/1.3.5/jquery.easy-autocomplete.min.js" integrity="sha512-Z/2pIbAzFuLlc7WIt/xifag7As7GuTqoBbLsVTgut69QynAIOclmweT6o7pkxVoGGfLcmPJKn/lnxyMNKBAKgg==" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/easy-autocomplete/1.3.5/easy-autocomplete.min.css" integrity="sha512-TsNN9S3X3jnaUdLd+JpyR5yVSBvW9M6ruKKqJl5XiBpuzzyIMcBavigTAHaH50MJudhv5XIkXMOwBL7TbhXThQ==" crossorigin="anonymous" />



<body class="">
<nav class="navbar navbar-expand-lg navbar-dark bg-dark bg-gradient">
  <div class="container-fluid mx-lg-5 mx-md-3 mx-sm-2 ">
    <%= link_to "Site S", home_path, class:"navbar-brand ms-3" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <!--
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        -->
        <% if current_user.nil? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Account
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="/users/sign_up">Sing in</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="/users/sign_in">Log in</a></li>
          </ul>
        </li>
          <% else %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <%= current_user.email %>
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><%= link_to 'Orders', orders_path, class: "dropdown-item"%></li>
              <li><%= link_to 'Cart', carts_path, class: "dropdown-item"%></li>
              <li><hr class="dropdown-divider"></li>
              <li><%= link_to 'Sing out', destroy_user_session_path,  method: :delete, class: "dropdown-item" %></li>
            </ul>
          </li>
          <% end %>
        <li class="nav-item">
        </li>
      </ul>
      <%= form_with url: searchdo_categories_path, class: "d-flex", method: :get, local:true do |f|  %>
        <%= f.search_field :product_name, class:"form-control", placeholder: "Search", data: { behavior: "autocomplete" } %>
        <%= f.submit "Search", class: "btn btn-outline-light" %>
      <%end %>
    </div>
  </div>
</nav>


<main class="container">
  <div class="row" >
  </div>
  <%= yield %>
</main>

</body>
<footer class="blog-footer mt-5" style="
  padding: 2.5rem 0;
  color: #727272;
  text-align: center;
  background-color: #f9f9f9;
  border-top: .05rem solid #e5e5e5;">
  <p>Shop template built on <a href="https://getbootstrap.com/">Bootstrap</a> by <a href="https://github.com/OleStan/blog_HW8">@oles</a>.</p>
  <p>
    <a href="#">Back to top</a>
  </p>
</footer>
</html>

app/views/pages/index.html.erb
<div class="row">
  <%= render 'categories/category'  %>
  <div class="col-9">
    <!--
    <div id="carouselExampleDark" class="carousel carousel-dark slide p-5" data-bs-ride="carousel">
      <ol class="carousel-indicators">
        <li data-bs-target="#carouselExampleDark" data-bs-slide-to="0" class="active"></li>
        <li data-bs-target="#carouselExampleDark" data-bs-slide-to="1"></li>
        <li data-bs-target="#carouselExampleDark" data-bs-slide-to="2"></li>
      </ol>
      <div class="carousel-inner">
        <div class="carousel-item active" data-bs-interval="10000">
          <img src="https://www.duragreen-electric.co.uk/img/technical.jpg" class="d-block w-100" alt="...">
          <div class="carousel-caption d-none d-md-block">
            <h5>First slide label</h5>
            <p>Nulla vitae elit libero, a pharetra augue mollis interdum.</p>
          </div>
        </div>
        <div class="carousel-item" data-bs-interval="2000">
          <img src="https://image.freepik.com/free-vector/online-shopping-promotion-social-media-mobile-app_257571-66.jpg" class="d-block w-100" alt="...">
          <div class="carousel-caption d-none d-md-block">
            <h5>Second slide label</h5>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
          </div>
        </div>
      </div>
      <a class="carousel-control-prev" href="#carouselExampleDark" role="button" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carouselExampleDark" role="button" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </a>
    </div>
  -->
    <% @categories.each do |categ|  %>
      <% next if categ.products.count <= 0 %>
      <% count_loop = 0 %>
      <h4 class="mt-4"><%= categ.name %></h4>
      <div class="row">
        <%categ.products.each do |product| %>
            <% break if count_loop >= 5%>
            <% count_loop+=1 %>
            <%= render product,  category: categ %>
        <% end %>
      </div>
    <% end %>
  </div>

</div>